#!/usr/bin/env python3
"""Erzeugt aus rudimente.py die Dart-Dateien lib/features/lessons/data/sheets/<id>_sheet.dart.

Aufruf: gen_dart.py <lib/features/lessons/data/sheets>
Danach `dart format` auf der Maschine mit Flutter.
"""
from __future__ import annotations

import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).parent))
from rudimente import SHEETS  # noqa: E402
from sheetlang import line_to_dart  # noqa: E402


def camel(ident: str) -> str:
    head, *rest = ident.split('_')
    return head + ''.join(p.capitalize() for p in rest)


def dart_str(s: str) -> str:
    return '"' + s.replace('\\', '\\\\').replace('"', '\\"').replace('$', '\\$') + '"'


def render(sheet) -> str:
    from sheetlang import note_to_dart
    c = camel(sheet.id)
    lines = sheet.parsed()
    body = '\n'.join(line_to_dart(ln) for ln in lines)
    pattern = '\n'.join('  ' + note_to_dart(n) + ',' for n in sheet.pattern_line().notes)
    lesson = '\n'.join(
        f'  TechniqueSection(\n    title: {dart_str(k)},\n    body: {dart_str(v)},\n  ),'
        for k, v in sheet.lesson.items())
    return f'''// GENERATED by tool/katalog/gen_dart.py from tool/katalog/rudimente.py —
// edit the Python source, not this file. Katalog Schritt 3a ({sheet.name}).
import '../../models/rudiment.dart';
import '../etude_dsl.dart';

/// {sheet.name}: the plain pattern, one bar — the PATTERN box on the info
/// page and the exercise's `sticking`.
final List<StrokeBeat> {c}Pattern = [
{pattern}
];

/// {sheet.name}: 8 lines of two bars plus an eight-bar challenge, composed
/// by the rule "as varied and groovy as possible" (Uli, 30.09.).
final List<ExerciseLine> {c}Sheet = [
{body}
];

/// Lesson sections for the info page — never shown on the practice screen.
const List<TechniqueSection> {c}Lesson = [
{lesson}
];
'''


def main(out_dir: pathlib.Path) -> None:
    out_dir.mkdir(parents=True, exist_ok=True)
    for s in SHEETS:
        path = out_dir / f'{s.id}_sheet.dart'
        path.write_text(render(s))
        print('wrote', path.name)


if __name__ == '__main__':
    main(pathlib.Path(sys.argv[1]))
